//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MastermindGameGUI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="MastermindService", ConfigurationName="ServiceReference1.IService", CallbackContract=typeof(MastermindGameGUI.ServiceReference1.IServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/Login", ReplyAction="MastermindService/IService/LoginResponse")]
        bool Login(string playerName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/Login", ReplyAction="MastermindService/IService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string playerName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/Logout", ReplyAction="MastermindService/IService/LogoutResponse")]
        void Logout(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/Logout", ReplyAction="MastermindService/IService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/RegisterNewPlayer", ReplyAction="MastermindService/IService/RegisterNewPlayerResponse")]
        void RegisterNewPlayer(string name, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/RegisterNewPlayer", ReplyAction="MastermindService/IService/RegisterNewPlayerResponse")]
        System.Threading.Tasks.Task RegisterNewPlayerAsync(string name, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GetRoomList", ReplyAction="MastermindService/IService/GetRoomListResponse")]
        string[] GetRoomList();
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GetRoomList", ReplyAction="MastermindService/IService/GetRoomListResponse")]
        System.Threading.Tasks.Task<string[]> GetRoomListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GetListOfPlayers", ReplyAction="MastermindService/IService/GetListOfPlayersResponse")]
        string[] GetListOfPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GetListOfPlayers", ReplyAction="MastermindService/IService/GetListOfPlayersResponse")]
        System.Threading.Tasks.Task<string[]> GetListOfPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GetPlayersInRoom", ReplyAction="MastermindService/IService/GetPlayersInRoomResponse")]
        string[] GetPlayersInRoom(string RoomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GetPlayersInRoom", ReplyAction="MastermindService/IService/GetPlayersInRoomResponse")]
        System.Threading.Tasks.Task<string[]> GetPlayersInRoomAsync(string RoomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/PlayerJoinRoom", ReplyAction="MastermindService/IService/PlayerJoinRoomResponse")]
        bool PlayerJoinRoom(string playerName, string roomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/PlayerJoinRoom", ReplyAction="MastermindService/IService/PlayerJoinRoomResponse")]
        System.Threading.Tasks.Task<bool> PlayerJoinRoomAsync(string playerName, string roomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/PlayerCreateRoom", ReplyAction="MastermindService/IService/PlayerCreateRoomResponse")]
        void PlayerCreateRoom(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/PlayerCreateRoom", ReplyAction="MastermindService/IService/PlayerCreateRoomResponse")]
        System.Threading.Tasks.Task PlayerCreateRoomAsync(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/PlayerLeaveRoom", ReplyAction="MastermindService/IService/PlayerLeaveRoomResponse")]
        void PlayerLeaveRoom(string playerName, string roomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/PlayerLeaveRoom", ReplyAction="MastermindService/IService/PlayerLeaveRoomResponse")]
        System.Threading.Tasks.Task PlayerLeaveRoomAsync(string playerName, string roomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/PlayerLeavePortal", ReplyAction="MastermindService/IService/PlayerLeavePortalResponse")]
        void PlayerLeavePortal(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/PlayerLeavePortal", ReplyAction="MastermindService/IService/PlayerLeavePortalResponse")]
        System.Threading.Tasks.Task PlayerLeavePortalAsync(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GetHiddenNumber", ReplyAction="MastermindService/IService/GetHiddenNumberResponse")]
        int[] GetHiddenNumber(string RoomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GetHiddenNumber", ReplyAction="MastermindService/IService/GetHiddenNumberResponse")]
        System.Threading.Tasks.Task<int[]> GetHiddenNumberAsync(string RoomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GetGuessResults", ReplyAction="MastermindService/IService/GetGuessResultsResponse")]
        string[] GetGuessResults(int[] guessNumbers, string roomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GetGuessResults", ReplyAction="MastermindService/IService/GetGuessResultsResponse")]
        System.Threading.Tasks.Task<string[]> GetGuessResultsAsync(int[] guessNumbers, string roomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/StartNewGame", ReplyAction="MastermindService/IService/StartNewGameResponse")]
        void StartNewGame(string RoomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/StartNewGame", ReplyAction="MastermindService/IService/StartNewGameResponse")]
        System.Threading.Tasks.Task StartNewGameAsync(string RoomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GameOver", ReplyAction="MastermindService/IService/GameOverResponse")]
        void GameOver(string roomName);
        
        [System.ServiceModel.OperationContractAttribute(Action="MastermindService/IService/GameOver", ReplyAction="MastermindService/IService/GameOverResponse")]
        System.Threading.Tasks.Task GameOverAsync(string roomName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="MastermindService/IService/gameFinished")]
        void gameFinished(string resulOfGame);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : MastermindGameGUI.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.DuplexClientBase<MastermindGameGUI.ServiceReference1.IService>, MastermindGameGUI.ServiceReference1.IService {
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool Login(string playerName, string password) {
            return base.Channel.Login(playerName, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string playerName, string password) {
            return base.Channel.LoginAsync(playerName, password);
        }
        
        public void Logout(string playerName) {
            base.Channel.Logout(playerName);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string playerName) {
            return base.Channel.LogoutAsync(playerName);
        }
        
        public void RegisterNewPlayer(string name, string pass) {
            base.Channel.RegisterNewPlayer(name, pass);
        }
        
        public System.Threading.Tasks.Task RegisterNewPlayerAsync(string name, string pass) {
            return base.Channel.RegisterNewPlayerAsync(name, pass);
        }
        
        public string[] GetRoomList() {
            return base.Channel.GetRoomList();
        }
        
        public System.Threading.Tasks.Task<string[]> GetRoomListAsync() {
            return base.Channel.GetRoomListAsync();
        }
        
        public string[] GetListOfPlayers() {
            return base.Channel.GetListOfPlayers();
        }
        
        public System.Threading.Tasks.Task<string[]> GetListOfPlayersAsync() {
            return base.Channel.GetListOfPlayersAsync();
        }
        
        public string[] GetPlayersInRoom(string RoomName) {
            return base.Channel.GetPlayersInRoom(RoomName);
        }
        
        public System.Threading.Tasks.Task<string[]> GetPlayersInRoomAsync(string RoomName) {
            return base.Channel.GetPlayersInRoomAsync(RoomName);
        }
        
        public bool PlayerJoinRoom(string playerName, string roomName) {
            return base.Channel.PlayerJoinRoom(playerName, roomName);
        }
        
        public System.Threading.Tasks.Task<bool> PlayerJoinRoomAsync(string playerName, string roomName) {
            return base.Channel.PlayerJoinRoomAsync(playerName, roomName);
        }
        
        public void PlayerCreateRoom(string playerName) {
            base.Channel.PlayerCreateRoom(playerName);
        }
        
        public System.Threading.Tasks.Task PlayerCreateRoomAsync(string playerName) {
            return base.Channel.PlayerCreateRoomAsync(playerName);
        }
        
        public void PlayerLeaveRoom(string playerName, string roomName) {
            base.Channel.PlayerLeaveRoom(playerName, roomName);
        }
        
        public System.Threading.Tasks.Task PlayerLeaveRoomAsync(string playerName, string roomName) {
            return base.Channel.PlayerLeaveRoomAsync(playerName, roomName);
        }
        
        public void PlayerLeavePortal(string playerName) {
            base.Channel.PlayerLeavePortal(playerName);
        }
        
        public System.Threading.Tasks.Task PlayerLeavePortalAsync(string playerName) {
            return base.Channel.PlayerLeavePortalAsync(playerName);
        }
        
        public int[] GetHiddenNumber(string RoomName) {
            return base.Channel.GetHiddenNumber(RoomName);
        }
        
        public System.Threading.Tasks.Task<int[]> GetHiddenNumberAsync(string RoomName) {
            return base.Channel.GetHiddenNumberAsync(RoomName);
        }
        
        public string[] GetGuessResults(int[] guessNumbers, string roomName) {
            return base.Channel.GetGuessResults(guessNumbers, roomName);
        }
        
        public System.Threading.Tasks.Task<string[]> GetGuessResultsAsync(int[] guessNumbers, string roomName) {
            return base.Channel.GetGuessResultsAsync(guessNumbers, roomName);
        }
        
        public void StartNewGame(string RoomName) {
            base.Channel.StartNewGame(RoomName);
        }
        
        public System.Threading.Tasks.Task StartNewGameAsync(string RoomName) {
            return base.Channel.StartNewGameAsync(RoomName);
        }
        
        public void GameOver(string roomName) {
            base.Channel.GameOver(roomName);
        }
        
        public System.Threading.Tasks.Task GameOverAsync(string roomName) {
            return base.Channel.GameOverAsync(roomName);
        }
    }
}
